import { RuneLine } from './runeTypes';
import { CELL_WIDTH, CELL_HEIGHT, OFFSET } from './grid';

export const LINES: Record<string, RuneLine> = {
   V_MID: { x1: CELL_WIDTH + OFFSET, y1: OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },
   V_LEFT_TOP: { x1: OFFSET, y1: OFFSET, x2: OFFSET, y2: CELL_HEIGHT + OFFSET },
   V_LEFT_BOTTOM: { x1: OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },
   V_RIGHT_TOP: { x1: CELL_WIDTH * 2 + OFFSET, y1: OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT + OFFSET },
   V_RIGHT_BOTTOM: { x1: CELL_WIDTH * 2 + OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },

   H_TOP_LEFT: { x1: OFFSET, y1: OFFSET, x2: CELL_WIDTH + OFFSET, y2: OFFSET },
   H_TOP_RIGHT: { x1: CELL_WIDTH + OFFSET, y1: OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: OFFSET },
   H_MID_TOP_LEFT: { x1: OFFSET, y1: CELL_HEIGHT + OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT + OFFSET },
   H_MID_TOP_RIGHT: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT + OFFSET },
   H_MID_BOTTOM_LEFT: { x1: OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT * 2 + OFFSET },
   H_MID_BOTTOM_RIGHT: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT * 2 + OFFSET },
   H_BOTTOM_LEFT: { x1: OFFSET, y1: CELL_HEIGHT * 3 + OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },
   H_BOTTOM_RIGHT: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT * 3 + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },

   DIAG_LEFT_TOP_TB: { x1: OFFSET, y1: OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT + OFFSET },
   DIAG_LEFT_TOP_BT: { x1: OFFSET, y1: CELL_HEIGHT + OFFSET, x2: CELL_WIDTH + OFFSET, y2: OFFSET },
   DIAG_RIGHT_TOP_TB: { x1: CELL_WIDTH + OFFSET, y1: OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT + OFFSET },
   DIAG_RIGHT_TOP_BT: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: OFFSET },
   DIAG_LEFT_BOTTOM_TB: { x1: OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },
   DIAG_LEFT_BOTTOM_BT: { x1: OFFSET, y1: CELL_HEIGHT * 3 + OFFSET, x2: CELL_WIDTH + OFFSET, y2: CELL_HEIGHT * 2 + OFFSET },
   DIAG_RIGHT_BOTTOM_TB: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT * 2 + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT * 3 + OFFSET },
   DIAG_RIGHT_BOTTOM_BT: { x1: CELL_WIDTH + OFFSET, y1: CELL_HEIGHT * 3 + OFFSET, x2: CELL_WIDTH * 2 + OFFSET, y2: CELL_HEIGHT * 2 + OFFSET },
};
