import { RuneLine } from './runeTypes';
import { CELL_WIDTH, CELL_HEIGHT } from './grid';

export const LINES: Record<string, RuneLine> = {
   V_MID: { x1: CELL_WIDTH, y1: 0, x2: CELL_WIDTH, y2: CELL_HEIGHT * 3 },
   V_LEFT_TOP: { x1: 0, y1: 0, x2: 0, y2: CELL_HEIGHT },
   V_LEFT_BOTTOM: { x1: 0, y1: CELL_HEIGHT * 2, x2: 0, y2: CELL_HEIGHT * 3 },
   V_RIGHT_TOP: { x1: CELL_WIDTH * 2, y1: 0, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT },
   V_RIGHT_BOTTOM: { x1: CELL_WIDTH * 2, y1: CELL_HEIGHT * 2, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT * 3 },

   H_TOP_LEFT: { x1: 0, y1: 0, x2: CELL_WIDTH, y2: 0 },
   H_TOP_RIGHT: { x1: CELL_WIDTH, y1: 0, x2: CELL_WIDTH * 2, y2: 0 },
   H_MID_TOP_LEFT: { x1: 0, y1: CELL_HEIGHT, x2: CELL_WIDTH, y2: CELL_HEIGHT },
   H_MID_TOP_RIGHT: { x1: CELL_WIDTH, y1: CELL_HEIGHT, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT },
   H_MID_BOTTOM_LEFT: { x1: 0, y1: CELL_HEIGHT * 2, x2: CELL_WIDTH, y2: CELL_HEIGHT * 2 },
   H_MID_BOTTOM_RIGHT: { x1: CELL_WIDTH, y1: CELL_HEIGHT * 2, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT * 2 },
   H_BOTTOM_LEFT: { x1: 0, y1: CELL_HEIGHT * 3, x2: CELL_WIDTH, y2: CELL_HEIGHT * 3 },
   H_BOTTOM_RIGHT: { x1: CELL_WIDTH, y1: CELL_HEIGHT * 3, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT * 3 },

   DIAG_LEFT_TOP_TB: { x1: 0, y1: 0, x2: CELL_WIDTH, y2: CELL_HEIGHT },
   DIAG_LEFT_TOP_BT: { x1: 0, y1: CELL_HEIGHT, x2: CELL_WIDTH, y2: 0 },
   DIAG_RIGHT_TOP_TB: { x1: CELL_WIDTH, y1: 0, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT },
   DIAG_RIGHT_TOP_BT: { x1: CELL_WIDTH, y1: CELL_HEIGHT, x2: CELL_WIDTH * 2, y2: 0 },
   DIAG_LEFT_BOTTOM_TB: { x1: 0, y1: CELL_HEIGHT * 2, x2: CELL_WIDTH, y2: CELL_HEIGHT * 3 },
   DIAG_LEFT_BOTTOM_BT: { x1: 0, y1: CELL_HEIGHT * 3, x2: CELL_WIDTH, y2: CELL_HEIGHT * 2 },
   DIAG_RIGHT_BOTTOM_TB: { x1: CELL_WIDTH, y1: CELL_HEIGHT * 2, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT * 3 },
   DIAG_RIGHT_BOTTOM_BT: { x1: CELL_WIDTH, y1: CELL_HEIGHT * 3, x2: CELL_WIDTH * 2, y2: CELL_HEIGHT * 2 },
};
