import { RuneDefinition, RuneLine } from './runeTypes';
import { LINES } from './lineLibrary';

const midRune = (...extraLines: RuneLine[]): RuneDefinition => {
   return { lines: [LINES.V_MID, ...extraLines] };
}

export const RUNE_MAP: Record<number, RuneDefinition> = {
   1: midRune(LINES.H_TOP_RIGHT),
   2: midRune(LINES.H_MID_TOP_RIGHT),
   3: midRune(LINES.DIAG_RIGHT_TOP_TB),
   4: midRune(LINES.DIAG_RIGHT_TOP_BT),
   5: midRune(LINES.DIAG_RIGHT_TOP_BT, LINES.H_TOP_RIGHT),
   6: midRune(LINES.V_RIGHT_TOP),
   7: midRune(LINES.V_RIGHT_TOP, LINES.H_TOP_RIGHT),
   8: midRune(LINES.V_RIGHT_TOP, LINES.H_MID_TOP_RIGHT),
   9: midRune(LINES.V_RIGHT_TOP, LINES.H_MID_TOP_RIGHT, LINES.H_TOP_RIGHT),
   10: midRune(LINES.H_TOP_LEFT),
   20: midRune(LINES.H_MID_TOP_LEFT),
   30: midRune(LINES.DIAG_LEFT_TOP_BT),
   40: midRune(LINES.DIAG_LEFT_TOP_TB),
   50: midRune(LINES.DIAG_LEFT_TOP_TB, LINES.H_TOP_LEFT),
   60: midRune(LINES.V_LEFT_TOP),
   70: midRune(LINES.V_LEFT_TOP, LINES.H_TOP_LEFT),
   80: midRune(LINES.V_LEFT_TOP, LINES.H_MID_TOP_LEFT),
   90: midRune(LINES.V_LEFT_TOP, LINES.H_MID_TOP_LEFT, LINES.H_TOP_LEFT),
   100: midRune(LINES.H_BOTTOM_RIGHT),
   200: midRune(LINES.H_MID_BOTTOM_RIGHT),
   300: midRune(LINES.DIAG_RIGHT_BOTTOM_BT),
   400: midRune(LINES.DIAG_RIGHT_BOTTOM_TB),
   500: midRune(LINES.DIAG_RIGHT_BOTTOM_TB, LINES.H_BOTTOM_RIGHT),
   600: midRune(LINES.V_RIGHT_BOTTOM),
   700: midRune(LINES.V_RIGHT_BOTTOM, LINES.H_BOTTOM_RIGHT),
   800: midRune(LINES.V_RIGHT_BOTTOM, LINES.H_MID_BOTTOM_RIGHT),
   900: midRune(LINES.V_RIGHT_BOTTOM, LINES.H_MID_BOTTOM_RIGHT, LINES.H_BOTTOM_RIGHT),
   1000: midRune(LINES.H_BOTTOM_LEFT),
   2000: midRune(LINES.H_MID_BOTTOM_LEFT),
   3000: midRune(LINES.DIAG_LEFT_BOTTOM_TB),
   4000: midRune(LINES.DIAG_LEFT_BOTTOM_BT),
   5000: midRune(LINES.DIAG_LEFT_BOTTOM_BT, LINES.H_BOTTOM_LEFT),
   6000: midRune(LINES.V_LEFT_BOTTOM),
   7000: midRune(LINES.V_LEFT_BOTTOM, LINES.H_BOTTOM_LEFT),
   8000: midRune(LINES.V_LEFT_BOTTOM, LINES.H_MID_BOTTOM_LEFT),
   9000: midRune(LINES.V_LEFT_BOTTOM, LINES.H_MID_BOTTOM_LEFT, LINES.H_BOTTOM_LEFT),
}
